# Generated by Django 5.2 on 2025-12-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="university_logo",
            field=models.ImageField(blank=True, null=True, upload_to="university/"),
        ),
    ]
