# Generated by Django 5.2 on 2025-12-28 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_class_resource"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[("mentor", "Mentor"), ("lead", "Lead")], max_length=20
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Position in club (e.g., Tech Lead)", max_length=200
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("quote", models.TextField(blank=True, null=True)),
                (
                    "tech_stack",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated or short summary",
                        null=True,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="team/")),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["role", "order", "name"],
            },
        ),
    ]
