# Generated by Django 5.2 on 2025-12-27 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_name", models.CharField(default="TARS", max_length=200)),
                (
                    "club_full_name",
                    models.CharField(
                        default="Technology and Automation Research Society",
                        max_length=500,
                    ),
                ),
                (
                    "club_motto",
                    models.TextField(
                        default="Pioneering the future of intelligent systems and automated solutions. Innovating at the intersection of technology, research, and human advancement."
                    ),
                ),
                (
                    "club_logo",
                    models.ImageField(blank=True, null=True, upload_to="club/"),
                ),
                (
                    "hero_background",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("youtube", "YouTube"),
                            ("discord", "Discord"),
                            ("email", "Email"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "url",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="CSS class for icon (e.g., 'fab fa-facebook')",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("logo", models.ImageField(upload_to="sponsors/")),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "collaboration_agenda",
                    models.TextField(help_text="Purpose or agenda of collaboration"),
                ),
                (
                    "collaboration_date",
                    models.DateField(help_text="Date when collaboration started"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
                "ordering": ["order", "-collaboration_date"],
            },
        ),
    ]
