# Generated by Django 5.2 on 2025-12-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_university_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('archived', 'Archived')], default='upcoming', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='classes/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(help_text="e.g., '4 weeks' or '10 hours'", max_length=100)),
                ('max_participants', models.IntegerField(default=30)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Meet link for online classes', null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location if applicable', max_length=300, null=True)),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='class_syllabus/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tutorial', 'Tutorial'), ('documentation', 'Documentation'), ('video', 'Video'), ('article', 'Article'), ('book', 'Book'), ('tool', 'Tool'), ('project', 'Project'), ('other', 'Other')], max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('file', models.FileField(blank=True, help_text='Upload file if applicable', null=True, upload_to='resource_files/')),
                ('external_link', models.URLField(blank=True, help_text='External URL if applicable', null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
